-- Compatibility notice
-- ====================
-- Database changes are now versioned in supabase/migrations/.
-- Use `supabase db push` for the linked project or `supabase db reset`
-- for local development. Do not maintain a second schema copy here.
